### ISSUE TITLE
User tasks and config get overridden by plugins

### ISSUE THREAD

**Issue by jsoverson** [apexlang/apex#30]
**Describe the bug**

Tasks or configuration defined in an `apex.yaml` can be overridden by any included plugins which can lead to unexpected and difficult-to-troubleshoot behavior.

**To Reproduce**

With any arbitrary apex spec, use the following `apex.yaml` and run `apex build`:

```yaml
spec: apex.axdl
plugins:
  - https://raw.githubusercontent.com/nanobus/iota/main/codegen/src/rust/plugin.ts
tasks:
  build: echo Hello World!
```

**Actual behavior**

The build step from the plugin runs

**Expected behavior**

Apex should output "Hello World!"

**Environment (where applicable):**

- OS: mac
- Architecture: m1
- Build Version 0.18
