### ISSUE TITLE
Regression: tasks from plugins aren't added to the task list

### ISSUE THREAD

**Issue by jsoverson** [apexlang/apex#33]
**Describe the bug**

Plugin tasks get dropped and aren't runnable.

**To Reproduce**

Run `apex list tasks` with this yaml and a generic spec.

```yaml
apex: spec.axdl
plugins:
  - https://raw.githubusercontent.com/nanobus/iota/main/codegen/src/rust/plugin.ts
```

**Actual behavior**

```
$ apex list tasks
┌──────────────────────┬─────────────────────────────────────────────┐
│ Name                 │ Description                                 │
└──────────────────────┴─────────────────────────────────────────────┘
  No results.
```

**Expected behavior**

```
apex list tasks
┌──────────────────────┬─────────────────────────────────────────────┐
│ Name                 │ Description                                 │
└──────────────────────┴─────────────────────────────────────────────┘
  all
  build
  etc
```

**Environment (where applicable):**

- OS mac
- Architecture m1
- Build Version 0.19

**Additional context** Add any other context about the problem here.
